# Generated by BangLish++ Compiler
# Target language: Python 3

bpp_a = 75
bpp_nts = 5.5
print(bpp_nts)
if (bpp_a > 90):
    print("Excellent")
elif (bpp_a > 80):
    print("Very Good")
elif ((bpp_a > 70) and (bpp_a < 80)):
    print("Good")
else:
    print("Needs Improvement")
bpp_i = 0
print("sakib is the KING")
while (bpp_i < 10):
    bpp_i = (bpp_i + 1)
    if ((bpp_i == 2) or (bpp_i == 4)):
        continue
    if ((bpp_i > 8) and (bpp_i < 10)):
        break
    print(bpp_i)
