# Generated by BangLish++ Compiler
# Target language: Python 3

a = 75
if (a > 90):
    print("Excellent")
elif (a > 80):
    print("Very Good")
elif ((a > 70) and (a < 80)):
    print("Good")
else:
    print("Needs Improvement")
i = 0
while (i < 10):
    i = (i + 1)
    if ((i == 2) or (i == 4)):
        continue
    if ((i > 8) and (i < 10)):
        break
    print(i)
